import { describe, expect, it } from "vitest";

import { amountAsInt, type RewardComputation } from "./reward";

const reward = (amount: number): RewardComputation => ({
  originMemberId: "o",
  recipientMemberId: "r",
  level: 1,
  metric: "points",
  baseAmount: amount,
  tier: "default",
  tierMultiplier: 1,
  levelFactor: 1,
  amount,
  context: {},
});

/**
 * `amountAsInt` is documented as a mirror of PHP
 * `FancyMlm\Referral\RewardComputation::amountAsInt`, which is `(int) round($v)`.
 *
 * It was not one. PHP's `round()` is **half away from zero**; JavaScript's
 * `Math.round()` is **half toward positive infinity**. They agree on every
 * positive value, which is exactly why this shipped and stayed: every test,
 * every demo and every seeder used positive rewards.
 *
 * They disagree on every negative half:
 *
 *   | amount | PHP | JS (before) |
 *   |--------|-----|-------------|
 *   | -0.5   | -1  | 0           |
 *   | -1.5   | -2  | -1          |
 *   | -2.5   | -3  | -2          |
 *
 * Reachable through configuration rather than only in theory. `levelFactors` is
 * `.map(Number)` straight off host config with no sign validation, so a negative
 * factor — a penalty tier, or a typo — produces a negative reward, and the two
 * backends then pay different amounts for the same event with nothing to
 * surface it.
 *
 * Pinned upstream as `shared/decimal` cases 0013-0018 in
 * `@particle-academy/fancy-conformance`, where the goldens were generated by
 * running the PHP reference rather than transcribed.
 */
describe("amountAsInt — matches PHP's round(), which is half away from zero", () => {
  it.each([
    [2.5, 3],
    [-2.5, -3], // Math.round gives -2
    [0.5, 1],
    [-0.5, -1], // Math.round gives -0
    [1.5, 2],
    [-1.5, -2], // Math.round gives -1
    [3.5, 4],
    [-3.5, -4], // Math.round gives -3
  ])("rounds %d to %d", (amount, expected) => {
    expect(amountAsInt(reward(amount))).toBe(expected);
  });

  it("is symmetric about zero", () => {
    // The property that actually matters for money: a credit and its matching
    // clawback must cancel exactly, or a ledger drifts by a unit per reversal.
    //
    // Stated as MAGNITUDE equality plus a zero sum, rather than
    // `f(-v) === -f(v)`. The two differ only at v = 0.1, where `-f(v)` is `-0`
    // and `f(-v)` is `+0` — deliberately, since negative zero is suppressed and
    // asserted separately below. Writing it the obvious way made this test fail
    // for a reason that had nothing to do with symmetry.
    for (const v of [0.5, 1.5, 2.5, 3.5, 2.4, 2.6, 7.5, 0.1]) {
      const positive = amountAsInt(reward(v));
      const negative = amountAsInt(reward(-v));

      expect(Math.abs(negative)).toBe(Math.abs(positive));
      expect(positive + negative).toBe(0);
    }
  });

  it("leaves non-half values exactly where they were", () => {
    // The regression half. The fix must not move any value that was already
    // correct — which is every value that is not an exact negative half.
    expect(amountAsInt(reward(2.4))).toBe(2);
    expect(amountAsInt(reward(-2.4))).toBe(-2);
    expect(amountAsInt(reward(2.6))).toBe(3);
    expect(amountAsInt(reward(-2.6))).toBe(-3);
    expect(amountAsInt(reward(0))).toBe(0);
    expect(amountAsInt(reward(42))).toBe(42);
    expect(amountAsInt(reward(-42))).toBe(-42);
  });

  it("never returns negative zero", () => {
    // `Math.sign(-0.4) * Math.round(0.4)` is -0, which is === 0 but serialises
    // as "-0" in JSON and would show up in a ledger export.
    expect(Object.is(amountAsInt(reward(-0.4)), -0)).toBe(false);
    expect(Object.is(amountAsInt(reward(-0)), -0)).toBe(false);
  });
});
